docs/UserGuide.md

[#25] Update descriptions for deleting student record and saving data

---

docs/DeveloperGuide.md

[#26] Update non-functional requirements

---

docs/UserGuide.md

[#32][User Guide] Add description for Edit feature

---

docs/DeveloperGuide.md

 [#35][Developer Guide] Add Target User Profile and Edit Feature Use Case

---

docs/AboutUs.md

Realised I made a small mistake in the link to my PPP 😅

[About Us] Edit link to my PPP

---

docs/UserGuide.md

[#46][#48] [User Guide] Add description for view feature, Add command summary table

---

docs/DeveloperGuide.md

[#53] [Developer Guide] Add value proposition

---

docs/UserGuide.md
docs/_config.yml

[UserGuide] Remove help command and update clear command

---

docs/UserGuide.md

[#61] Update quick start section with Class-ify details

---

docs/index.md

[#57] Update index.md with Class-ify description

---

docs/UserGuide.md

[#55][User Guide] Add Class-ify overview into user guide and delete Command Format segment

---

src/main/java/seedu/address/logic/commands/ViewAllCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/ViewAllCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Change the command name from list to viewAll. Functionality remains the same.

[Development] Refactor list to viewAll command #96

---

src/main/java/seedu/address/model/person/Id.java
src/main/java/seedu/address/model/person/Person.java

Id field is needed for future implementation of a `Student` class, which currently is not supported in `Person` class.
Having a new id class allows for abstraction of the various identity fields of a person.
Let's:
- Create a new `Id` class
- Implement method to validate a given id string
- Note: An id is the last 4 digits of a NRIC, hence it should consist of 3 numerical digits and 1 alphabetical character
- Add in the new id field in the `Person` class

[User Story] Add new id field to Person

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/storage/JsonSerializableStudentRecord.java
src/main/java/seedu/address/storage/JsonStudentRecordStorage.java
src/main/java/seedu/address/storage/Storage.java
src/main/java/seedu/address/storage/StorageManager.java
src/main/java/seedu/address/storage/StudentRecordStorage.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/storage/JsonStudentRecordStorageTest.java
src/test/java/seedu/address/storage/StorageManagerTest.java

[#78] Rename instances of AddressBook to StudentRecord in Storage

---

docs/UserGuide.md

[#108] [User Guide] Update view command format in user guide

---

docs/DeveloperGuide.md

The introduction includes purpose, target audience and a short description of Class-ify.
Numbering is added to each different section of the developer guide for clarity.
User stories have been updated. More to be added in the future.

[Developer Guide] Update developer guide structure

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/StudentRecordParser.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/logic/parser/StudentRecordParserTest.java

[#125] [Enhancement] Rename View command to Find

---

docs/UserGuide.md

The introduction includes a short description of Class-ify, who the guide is for and how to use the guide. I added some notations such as `Tips`, `Notes` and `Cautions` that we could use throughout the guide to help new users.
Numbering is added to each different section of the user guide for clarity.
New users may be confused about some terms that we use throughout the guide so this section may be helpful to them.

[User Guide] Update user guide structure

---

docs/DeveloperGuide.md
src/main/java/seedu/classify/ui/StudentCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/StudentListCard.fxml

- Grades are highlighted in a box, similar to how tags are displayed previously in AB3
- This allows for better views of students' academic details by teachers
Did a minor fix to the developer guide format under the model component section.

[UI] Update student card UI with grades

---

docs/UserGuide.md

UG structure is updated to the following 
```
Introduction
What is classify?
Who is this guide for?
How to use this user guide [Section added]
Symbols
Parameters
Format
Quick Start
Navigating the Display
Features
Managing student records [Section added]
Adding a new student record
Clearing all student records
Deleting a student record
Editing a new student record
Managing display of student records [Section added]
Finding a student record
Toggling view
Viewing all student records
Viewing student records from a class
Exam statistics [Section added]
Getting exam statistics
Miscellaneous  [Section added]
Exiting the application
Viewing help
Saving the data
FAQ
Glossary
Command Summary
```

Update Structure of UG

---

src/main/java/seedu/classify/logic/commands/DeleteCommand.java
src/main/java/seedu/classify/logic/commands/ExitCommand.java
src/main/java/seedu/classify/logic/commands/FindCommand.java
src/main/java/seedu/classify/logic/commands/HelpCommand.java
src/main/java/seedu/classify/logic/commands/ViewAllCommand.java
src/main/java/seedu/classify/logic/commands/ViewClassCommand.java
src/main/java/seedu/classify/logic/commands/exceptions/CommandException.java
src/main/java/seedu/classify/model/student/Id.java
src/test/java/seedu/classify/storage/JsonStudentRecordStorageTest.java

- Fix bug which occurs when issuing a delete command that deletes an invalid student name/ID and the student list will disappear
- General code quality improvements

[Code Quality] Fix DeleteCommand bug and improve code quality

---

docs/DeveloperGuide.md

[#167][Developer Guide] Update use cases

---

src/main/java/seedu/classify/MainApp.java
src/main/java/seedu/classify/commons/core/Messages.java
src/main/java/seedu/classify/logic/commands/EditCommand.java
src/main/java/seedu/classify/logic/commands/ViewClassCommand.java
src/main/java/seedu/classify/storage/StorageManager.java
src/test/java/seedu/classify/logic/LogicManagerTest.java
src/test/java/seedu/classify/logic/commands/AddStudCommandIntegrationTest.java
src/test/java/seedu/classify/logic/commands/AddStudCommandTest.java
src/test/java/seedu/classify/logic/commands/ViewClassCommandIntegrationTest.java
src/test/java/seedu/classify/logic/commands/ViewClassCommandTest.java
src/test/java/seedu/classify/logic/parser/ParserUtilTest.java
src/test/java/seedu/classify/logic/parser/ViewClassCommandParserTest.java
src/test/java/seedu/classify/storage/JsonStudentRecordStorageTest.java

Fixes #171 
- Added in more unit test case and integration test case for ViewClass command.
- Changed success message displayed for ViewClass command to account for singular person in class. (For grammatical accuracy)
- Remove final instances of AddressBook with StudentRecord

[#171][Enhancement][Bug] Add more test cases and change ViewClass success message

---

src/main/java/seedu/classify/logic/commands/EditCommand.java
src/main/java/seedu/classify/model/Model.java
src/main/java/seedu/classify/model/ModelManager.java
src/main/java/seedu/classify/model/StudentRecord.java
src/main/java/seedu/classify/model/student/UniqueStudentList.java
src/test/java/seedu/classify/logic/commands/AddStudentCommandTest.java

Current bug:
- was able to edit a student to have the same name as another student in the list
- there was an error in checking for the duplicate student
Solution: 
- created a new method to check for duplicate student excluding the student to be changed
- the error happens because the edited student can have the same id as the student to be edited, hence Model#hasStudent does not work as intended

[#198] [Bug] Bugfix edit command

---

docs/UserGuide.md
src/main/java/seedu/classify/commons/core/Messages.java
src/main/java/seedu/classify/logic/commands/FindCommand.java
src/main/java/seedu/classify/logic/commands/ViewStatsCommand.java
src/main/java/seedu/classify/model/student/Email.java
src/main/java/seedu/classify/model/student/Name.java
src/main/java/seedu/classify/model/student/Phone.java
src/main/java/seedu/classify/model/student/Student.java
src/test/java/seedu/classify/logic/commands/FindCommandTest.java
src/test/java/seedu/classify/logic/commands/ViewStatsCommandTest.java

Changes:
- Change UG to include . in header numbering to standardise with DG
- Add a new MESSAGE_SINGLE_PERSON_LISTED_OVERVIEW to account for single person found (Grammatical fix)
- Add line breaks and isEmpty checks to optional fields in Student `toString` method for better UI display.
- Fix ViewStats throwing error bug. Instead of throwing an exception it now returns a CommandResult with the exception error message.

[Bug][Enhancement] Made some display message changes and fix ViewStats Bug

---

docs/DeveloperGuide.md

- Fix the numbering format to match that of the user guide
- Add "How to use this developer guide" subsection under the introduction section

[Developer Guide] Fix comestic issues

---

src/main/resources/view/MainWindow.fxml

Fixes #206 
- Window size set to minimum 800w x 600h
- So that the result box will not be cut off

[#206][UI] Set minimum window size

---

src/main/java/seedu/classify/logic/parser/EditCommandParser.java
src/test/java/seedu/classify/logic/parser/EditCommandParserTest.java
src/test/java/seedu/classify/logic/parser/StudentRecordParserTest.java
src/test/java/seedu/classify/testutil/StudentUtil.java

[#233][Edit Command] Fix empty exam input

---

docs/UserGuide.md

[User Guide] Add note about case insensitivity of inputs to delete command section

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/index.md

- Add glossary link to technical terms
- Add usage for toggleView
- Place FAQ in a table for better viewing
- Clean up some grammer and standardise formatting

[Documentation] Clean up user guide

---

docs/DeveloperGuide.md

Besides formatting, refined the Manual Testing section to reflect the correct outcomes for each test case.

[DG] Update formatting and correct out of date information
